### ISSUE TITLE
bpy.ops.wm.search_menu()?

### ISSUE THREAD

**Issue by cyaoeu** [miniukof/bl-leader_key#1]
Hi, interesting addon!
I guess the key you would want for Leader Key is Space, but I really like the space bar search, so I thought I could have Space being Leader Key and the space bar search being Space inside Leader Key, however it seems like the search menu doesn't show up even when you set the correct context. Any idea what could be wrong?

**Comment by cyaoeu** [comment]
Never mind, fixed it by calling it with bpy.ops.wm.search_menu("INVOKE_REGION_WIN").

**Comment by adam-wolski** [comment]
Happy that you managed to make it work ^^
