### ISSUE TITLE
Use of lettered registers

### ISSUE THREAD

**Issue by jaggzh** [miniukof/bl-leader_key#2]
I'm pleased someone started incorporating vim-like efficiency into Blender, as I've wanted it for a long time!
I'm wonder what can I do, with your code, to capture additional keystrokes after the provided one(s)?

For instance, let's say I wanted to store a setting in any keyboard key (like vim's registers):
Let's say we have a <leader>, then r is to record a setting, and I choose to store the setting in the 'c' key:
I'd want to mouse-over a setting, hit <leader>, r, c
Then to restore the setting, I'd use <leader>, s, c

To add another setting to the 'c' register, I'd use <leader>, r, C (ie. capitalized register will append).

I wrote this doc some time ago:
https://wiki.blender.org/index.php/User:jaggz/efficiency--vim-inspired

**Comment by adam-wolski** [comment]
Hah, never noticed that I received issues on repo ^^'

I think your suggestion is quite cool. Not sure how useful in the end, but cool for sure.
If I ever get some time maybe I'll look into it :D

But that would be different plugin.
